/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    work: Work;
    posts: Post;
    craft: Craft;
    pageviews: Pageview;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    work: WorkSelect<false> | WorkSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    craft: CraftSelect<false> | CraftSelect<true>;
    pageviews: PageviewsSelect<false> | PageviewsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    profile: Profile;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work".
 */
export interface Work {
  id: string;
  title: string;
  /**
   * URL-safe identifier. Auto-filled from title on first save.
   */
  slug: string;
  /**
   * e.g. "Marketing Website"
   */
  subtitle: string;
  /**
   * Leave empty to auto-generate from the live site URL
   */
  cover?: (string | null) | Media;
  /**
   * Display date, e.g. "Mar 2026"
   */
  date: string;
  /**
   * Optional live site URL
   */
  href?: string | null;
  /**
   * One-line summary shown on project cards
   */
  description: string;
  /**
   * Tech stack entries e.g. Next.js, Tailwind
   */
  tech?: string[] | null;
  /**
   * Full project writeup
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional gallery images shown below the body
   */
  images?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sort order — lower numbers appear first (1 = top)
   */
  order: number;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * URL-safe identifier. Auto-filled from title on first save.
   */
  slug: string;
  date: string;
  /**
   * e.g. "6 min read"
   */
  readTime: string;
  /**
   * Shown on the index page and homepage preview
   */
  excerpt: string;
  /**
   * Optional cover image shown at the top of the post and used as default OG image
   */
  coverImage?: (string | null) | Media;
  /**
   * Topic tags e.g. nextjs, performance
   */
  tags?: string[] | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "craft".
 */
export interface Craft {
  id: string;
  title: string;
  /**
   * URL-safe identifier. Auto-filled from title on first save.
   */
  slug: string;
  /**
   * Display date, e.g. "Apr 2026"
   */
  date: string;
  /**
   * One-line summary shown on craft cards
   */
  description: string;
  /**
   * Topic tags e.g. animation, button
   */
  tags?: string[] | null;
  /**
   * Optional cover image for the craft item
   */
  cover?: (string | null) | Media;
  /**
   * Optional credit for the craft item
   */
  credit?: {
    name?: string | null;
    /**
     * Optional link for the credit
     */
    href?: string | null;
  };
  /**
   * Sort order — lower numbers appear first (1 = top)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Self-hosted pageview log. Surfaced via the analytics view.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageviews".
 */
export interface Pageview {
  id: string;
  path: string;
  country?: string | null;
  city?: string | null;
  region?: string | null;
  device: 'desktop' | 'mobile' | 'tablet' | 'bot';
  browser?: string | null;
  os?: string | null;
  referrer?: string | null;
  ipHash: string;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'work';
        value: string | Work;
      }
    | {
        relationTo: 'posts';
        value: string | Post;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'work';
        value: string | Work;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'craft';
        value: string | Craft;
      } | null)
    | ({
        relationTo: 'pageviews';
        value: string | Pageview;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work_select".
 */
export interface WorkSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  cover?: T;
  date?: T;
  href?: T;
  description?: T;
  tech?: T;
  body?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  readTime?: T;
  excerpt?: T;
  coverImage?: T;
  tags?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "craft_select".
 */
export interface CraftSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  description?: T;
  tags?: T;
  cover?: T;
  credit?:
    | T
    | {
        name?: T;
        href?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageviews_select".
 */
export interface PageviewsSelect<T extends boolean = true> {
  path?: T;
  country?: T;
  city?: T;
  region?: T;
  device?: T;
  browser?: T;
  os?: T;
  referrer?: T;
  ipHash?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: string;
  /**
   * e.g. "Rafey" — shown in browser tab and avatar
   */
  shortName: string;
  /**
   * e.g. "Rizwan Nur Rafey" — shown when name is expanded
   */
  fullName: string;
  /**
   * Subtitle below your name
   */
  role: string;
  /**
   * Profile photo. Leave empty to use the default /rafey.png.
   */
  avatar?: (string | null) | Media;
  /**
   * Large serif italic text at the top of the page
   */
  headline: string;
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  recent: {
    lead?: string | null;
    company: {
      name: string;
      href: string;
      /**
       * Brand hex color, e.g. #5B3FFF
       */
      brand?: string | null;
    };
    tail?: string | null;
  };
  past?: {
    lead?: string | null;
    companies?:
      | {
          name: string;
          href: string;
          brand?: string | null;
          id?: string | null;
        }[]
      | null;
    tail?: string | null;
  };
  searching?: string | null;
  /**
   * Shown in the bordered availability box
   */
  availability?: string | null;
  /**
   * Cal.com booking URL
   */
  bookCall?: string | null;
  socials?:
    | {
        label: string;
        href: string;
        kind: 'twitter' | 'instagram' | 'github' | 'linkedin' | 'resume' | 'mail';
        id?: string | null;
      }[]
    | null;
  /**
   * IANA timezone, e.g. "Asia/Dhaka"
   */
  timezone?: string | null;
  /**
   * Short label shown in footer, e.g. "BDT"
   */
  timezoneAbbr?: string | null;
  /**
   * Your admin account — links this profile to your login.
   */
  linkedUser?: (string | null) | User;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  shortName?: T;
  fullName?: T;
  role?: T;
  avatar?: T;
  headline?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  recent?:
    | T
    | {
        lead?: T;
        company?:
          | T
          | {
              name?: T;
              href?: T;
              brand?: T;
            };
        tail?: T;
      };
  past?:
    | T
    | {
        lead?: T;
        companies?:
          | T
          | {
              name?: T;
              href?: T;
              brand?: T;
              id?: T;
            };
        tail?: T;
      };
  searching?: T;
  availability?: T;
  bookCall?: T;
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        kind?: T;
        id?: T;
      };
  timezone?: T;
  timezoneAbbr?: T;
  linkedUser?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}